### ISSUE TITLE
Documentation on Teleportation for Quantum Circuit Mapping

### ISSUE THREAD

**Issue by pehamTom** [cda-tum/qmap#117]
The current documentation doesn't include any information on the teleportation feature for the heuristic mapper.

I suggest introducing a subsection regarding this topic in the *Heuristic Mapper* section in `Mapping.rst`.

**Comment by burgholzer** [comment]
@hillmich could you please take care of this once #114 is merged?

**Comment by burgholzer** [comment]
Just pinging here, so it does not get lost. Would be great to have a separate section in the documentation for this. Could also be a separate Jupyter notebook that shows some very simple examples and how teleportation can be used.
